language: ruby
rvm:
  - 2.4
script:
  - bundle exec jekyll build --future
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
branches:
  only:
  - gh-pages
  - /.*/
notifications:
  on_success: never
  on_failure: always