title: Graph AI Conference Deadlines # (Maintained by @zxsong)
# email: zxsong@cse.cuhk.edu.hk
description: Countdowns to top Graph AI conference deadlines
author: Zixing SONG

domain: "anthonysong98.github.io"
baseurl: "/graph-ai-deadlines"

github_username: anthonysong98
github_repo: graph-ai-deadlines

markdown: kramdown

include: ['_pages']